### ISSUE TITLE
nogle link til anmeldelser på biblo fejler - blank side, søger....

### ISSUE THREAD

**Issue by kkdbc** [DBCDK/biblo-admin#104]
tester på https://biblo-admin.demo.dbc.dk/ 
Reviews ==>
fx: 

w0h00!  3   775100-katalog:42946400     718500  jaco799j    26-04-2016 13:48    View on Biblo.dk

Super bog om den døde hest.    5   870970-basis:29567085   724002  kira1589    29-04-2016 11:54    View on Biblo.dk

**Comment by kkdbc** [comment]
kan det være fordi anmeldelse ikke eksisterer længere? Burde ikke være på listen så.

**Comment by KiraH** [comment]
Det er en anmeldelse jeg har slettet.

**Comment by kallehauge** [comment]
Det kunne meget godt ligne den samme fejl som Claus oplevede, da han lavede demo til receptionen i fredags, da han ville linke en review til en gruppe, og der var 3 slettede reviews som dukkede op. - Men umiddelbart er det ikke en fejl hos os, da vi ikke cacher nogen lister ☺️

**Comment by kallehauge** [comment]
Jeg vælger ikke at lukke det her issue, indtil det er blevet bekræftet af UX teamet. @DBCDK/ux-team er det noget i har hørt nærmere om fra Claus?

**Comment by kasperg** [comment]
Der er kommet flere værdier med på reviews - bl.a. `markedAsDeleted`.

![strongloop api explorer 2016-06-06 10-10-26](https://cloud.githubusercontent.com/assets/73966/15815692/0c3ef636-2bcf-11e6-943e-ebe25fc05c28.png)

Dem viser vi ikke og vi bruger dem heller ikke i forbindelse med filtrering. For at løse dette skal vi:
1. Opdatere vores klientkode
2. Tilføje et fast filter der altid frasorterer slettede reviews eller giver udvidede filtreringsmuligheder til brugeren
3. Evt. opdatere visningen af reviews så `markedAsDeleted` også kommer med.

**Comment by kasperg** [comment]
Dette er rettet og rullet ud produktion nu.

**Comment by kasperg** [comment]
Jeg lukker denne.
