### ISSUE TITLE
article type er mandatory, men jeg kan ikke vælge noget i dropdown

### ISSUE THREAD

**Issue by kkdbc** [DBCDK/biblo-admin#106]
![select value](https://cloud.githubusercontent.com/assets/18323273/15741628/cc171c26-28ba-11e6-86bb-3030492487cb.png)

Muligvis er det blot fordi jeg ikke forstår....

**Comment by kallehauge** [comment]
Yes, det er vist en kommunikationsfejl :smile:
Hvis man går ind under `/admin/structure/taxonomy/manage/article_types/overview`, så skal man oprette artikeltyperne ☺️ 

**OBS!** Det kræver en administrator-rolle, så det må være Anders :)
