### ISSUE TITLE
Link til side i frontend fejler fra artikeloversigtsside 

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo-admin#114]
Links for artiklerne på denne side https://admin.biblo.dk/admin/content linker ikke til frontend, men til admin. Fx. linker "testartikel" til https://admin.biblo.dk/sommerbogen/test-klaus i stedet for til https://biblo.dk/sommerbogen/test-klaus

**Comment by kasperg** [comment]
@AndersFriisBrodsgaard: Dette er rettet på staging nu. Der er lavet et separat link til at vise indholdet på biblo.dk som det også er tilfældet ved de andre lister.

![indhold biblo admin 2016-06-15 10-23-57](https://cloud.githubusercontent.com/assets/73966/16072870/58dd4d74-32e3-11e6-9538-5b87a04deeb2.png)
