### ISSUE TITLE
Library employee kan ikke se fanen Reviews

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo-admin#123]
Visse adminbrugere kan ikke se fanen Reviews, selv om de har rollen Library Employee. Andre brugere med denne rolle kan godt. 

To eksempler:
Stine Hansen ( https://admin.biblo.dk/user/6/edit?destination=/admin/people )
Charlotte Juul ( https://admin.biblo.dk/user/5/edit?destination=/admin/people )

For at de to kan moderere anmeldelser, har de på nuværende tidspunkt fået tilknyttet administrator-rollen.

**Comment by kasperg** [comment]
@AndersFriisBrodsgaard: Er I nået videre med denne?

**Comment by vibjerg** [comment]
Problemet er løst for de to brugere
