### ISSUE TITLE
Procedure ved opret bruger / nulstil password 

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo-admin#128]
Når man nulstiller sit password får man tilsendt en mail med et engangslink til at logge ind ,men man skal bruge sit password for ændre det. Og det har man ikke, hvis man fx har glemt det.

Det samme gælder ved oprettelse af en bruger - den nyoprettede bruger får tilsendt et engangslink, men skal bruge sit eksisterende password for at ændre password - og det har brugeren ikke fået tilsendt.

**Comment by kasperg** [comment]
Det må være en misforståelse.

Man skal ikke bruge sit eksisterende password for at ændre password. Det står også i brugergrænsefladen:

![admin biblo admin 2016-08-03 15-18-46](https://cloud.githubusercontent.com/assets/73966/17366870/bec93492-598d-11e6-8a81-3d6fbfe3215a.png)

**Comment by AndersFriisBrodsgaard** [comment]
Den skærm, jeg får, når jeg har nulstillet password, ser sådan her ud:
https://www.dropbox.com/s/cx7meqwl4l190xx/Screenshot%202016-08-08%2014.03.56.png?dl=0
![screenshot 2016-08-08 14 03 56](https://cloud.githubusercontent.com/assets/18284484/17479153/0d105e6e-5d71-11e6-9b79-5d3df2cf554d.png)

Hvor der øverst står "Current password"

**Comment by AndersFriisBrodsgaard** [comment]
Jeg logger ind med engangslinket og vælger "Edit profile" i menuen øverst. 
Hvis jeg prøver at ændre password ved at udfylde de to felter længere nede på siden med et nyt password, får jeg følgende besked:
"Your current password is missing or incorrect; it's required to change the Password."

Måske er det fordi, jeg ikke kommer til den rigtige side efter at have brugt engangslinket.

**Comment by kasperg** [comment]
I ovenstående screenshot kommer jeg fra engangslinket direkte ind på den side, hvor man kan skifte passwordet og har derfor ikke behov for at vælge "Edit profile". Gør du ikke det?
