### ISSUE TITLE
Alfabetisk sortering af biblioteksvæsener i dropdown

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo-admin#135]
Redaktørerne har meget svært ved at finde deres bibliotek/væsen i dropdown'en "Library" under "Filter list" for Reviews. Væsenerne står i rækkefølge efter ISILnr. En alfabetisk A-Å sortering vil være at foretrække i stedet for.

**Comment by vibjerg** [comment]
Bibliotekerne står sorteret alfabetisk under væsen.

**Comment by AndersFriisBrodsgaard** [comment]
Tjekket OK på demo
