### ISSUE TITLE
Det er ikke muligt at oprette en ny kampagne

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo-admin#137]
Jeg får fejlen "Unable to create/update the campaign. Please try again later" når jeg forsøger at oprette en kampagne på https://biblo-admin.demo.dbc.dk/

**Comment by kasperg** [comment]
Hvilke data indtastede du? 

Jeg tænker at det skyldes manglende logo og vil dermed blive adresseret igennem #138. Jeg kan også se at der er en fejl netop vedr. det i loggen.

**Comment by AndersFriisBrodsgaard** [comment]
Den er fin, kan oprette nu.
