### ISSUE TITLE
Api endpoint returnerer fejl 500 hvis menupunkt oprettes med relativ url.

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/biblo-admin#142]
Hvis man opretter et menupunkt med en relativ url f.eks. /grupper, så kan man ikke hente menuen vi api endpoint, men får en fejl 500.

**Comment by kasperg** [comment]
Jeg har rullet en rettelse ud på staging nu.

**Comment by vibjerg** [comment]
Fixed
