### ISSUE TITLE
hentning af logoer til kampagner fejler

### ISSUE THREAD

**Issue by jacobandresen** [DBCDK/biblo-admin#143]
Iøjeblikket virker flg url:  http://biblo-admin.demo.dbc.dk/sites/default/files/campaigns/logos/svg/biblo_B_RGB.png  (angivet som svg)

hvorimod flg ikke virker  : 

small: 'http://biblo-admin.demo.dbc.dk/sites/default/files/styles/small/public/campaigns/logos/img/biblo_B_RGB.png?itok=6VPgmOsW',
     medium: 'http://biblo-admin.demo.dbc.dk/sites/default/files/styles/medium/public/campaigns/logos/img/biblo_B_RGB.png?itok=LkoGzEUO',
     large: 'http://biblo-admin.demo.dbc.dk/sites/default/files/styles/large/public/campaigns/logos/img/biblo_B_RGB.png?itok=18tlJtpX',

**Comment by jacobandresen** [comment]
Jeg tænker at det måske er relateret til at billederne kan være blevet slettet ifm redeploy.

**Comment by jacobandresen** [comment]
Jeg noterer at http://biblo-admin.demo.dbc.dk/sites/default/files/campaigns/logos/svg/biblo_B_RGB.png  ikke kan hentes idag.

**Comment by jacobandresen** [comment]
@KiraH har rettet deploy'et til for biblo-admin.demo

**Comment by KiraH** [comment]
Nu kan man tilgå billederne på ovenstående URL'er.
