### ISSUE TITLE
Billeder uploadet til kampagne slettes automatisk med kort mellemrum

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo-admin#149]
Logo-filer, der uploades til kampagner registreres som "temporary" og med antal anvendelser som 0. Derfor slettes de efter kort tid af en automatisk oprydning i admin. Det skal de ikke.
@kkdbc

**Comment by kasperg** [comment]
Hmm - [vi markerer dem ellers explicit som permanent](https://github.com/DBCDK/biblo-admin/blob/develop/web/modules/custom/dbcdk_community_content/src/Form/CampaignForm.php#L255). Det må vi se på.

**Comment by AndersFriisBrodsgaard** [comment]
Takker. De ligger som temp her: https://admin.biblo.dk/admin/content/files

**Comment by AndersFriisBrodsgaard** [comment]
@kasperg Du må gerne se om du kan finde tid til at debugge denne. Vi skal pt. sidde og uploade billederne mindst en gang dagligt.
