### ISSUE TITLE
Indsættelse af "Best rated works"-widget resulterer i helt tom side. 

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo-admin#174]
Se fx denne sektionsside
https://admin-stg.biblo.dk/node/5/edit?destination=/admin/content
https://biblo.demo.dbc.dk/section-page

**Comment by vibjerg** [comment]
Fejlen ligger ikke i admin men i biblo (https://github.com/DBCDK/biblo/issues/387)
