### ISSUE TITLE
BestRatedWorks widget skal indeholde en fuld liste af worktypes

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/biblo-admin#179]
Der skal defineres en liste over de worktypes som skal kunne vælges i admin

**Comment by vibjerg** [comment]
@AndersFriisBrodsgaard gider du definere de typer, som skal være med

**Comment by AndersFriisBrodsgaard** [comment]
[
  {
    "worktype": "book",
    "id": 1
  },
  {
    "worktype": "article",
    "id": 2
  },
  {
    "worktype": "music",
    "id": 3
  },
  {
    "worktype": "other",
    "id": 4
  },
  {
    "worktype": "sheetmusic",
    "id": 5
  },
  {
    "worktype": "movie",
    "id": 6
  },
  {
    "worktype": "audiobook",
    "id": 7
  },
  {
    "worktype": "periodica",
    "id": 8
  },
  {
    "worktype": "game",
    "id": 9
  },
  {
    "worktype": "literature",
    "id": 10
  },
  {
    "worktype": "none",
    "id": 11
  },
  {
    "worktype": "map",
    "id": 12
  },
  {
    "worktype": "analysis",
    "id": 13
  }
]
