### ISSUE TITLE
Opdater drupal og plugins til nyeste version

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/biblo-admin#193]
Drupal og plugin skal opdateres.

Accept: Admin-delen skal gennemprøves grundigt og accept er at det hele virker.

**Comment by vibjerg** [comment]
Det var ikke muligt at rulle fixet i produktion, da opdatering af konfigurationen fejlede. Forsøger i stedet at bryde opdateringen op i mindre bider.

**Comment by AndersFriisBrodsgaard** [comment]
Har testet lidt rundt omkring, og det ser ud til at virke som det skal i admin. Der optræder dog nogle fejl i grænsefladen. Har konstateret følgende:
- [x] Der kommer dog en del errors og warnings på fx forsiden, https://biblo.demo.dbc.dk/.
- [x] Der mangler forsider på nogle af bøgerne i bestemte widgets, fx "Editorially selected materials" på forsiden.
- [x] Der kommer ikke indhold i widget'en "Latest posts all groups" ("Seneste indlæg i grupperne", nederst på forsiden.
- [x] Når jeg logger ind i frontend, ender jeg på denne side: https://biblo.demo.dbc.dk/https://moreinfo.addi.dk/2.11/more_info_get.php?lokalid=29397872&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=62c887ab6a1f5feecaee
- [x] Color pickeren i admin virker ikke (bruges til valg af baggrundsfarve i de forskellige widgets). 

Fejlene kan jo også skyldes opdateringer i frontend, men det kan jeg ikke gennemskue.

**Comment by hrmoller** [comment]
De warnings der kommer er relateret til reacts parsning. Der opstår nogle elementer med samme `key` hvorfor react brokker sig og det er i hvert fald ikke relateret til biblo-admin.

Der kommer 20 fejl (på den nuværende biblo.demo forside) der er relateret til LatestPosts widget hvilket skyldes at der hentes posts der af en eller anden årsag ikke er associeret med nogen gruppe. 
Se f.eks. responsen på dene request `curl -X GET --header "Accept: application/json" "http://biblocs-stg.dbc.dk/api/Posts/181"`
```
{
  "title": " ",
  "content": "undefined",
  "timeCreated": "2017-11-21T14:45:03.000Z",
  "groupDeleted": false,
  "markedAsDeleted": null,
  "id": 181,
  "postownerid": 13,
  "postcontainergroupid": null,
  "postid": null,
  "groupid": null,
  "attachedReviewId": null
}
```

**Comment by hrmoller** [comment]
De manglende forsider løses med https://github.com/DBCDK/biblo/issues/707

**Comment by hrmoller** [comment]
Det underlige redirect efter login skyldes sandsynligvis en fejl i biblo, ikke biblo-admin

**Comment by AndersFriisBrodsgaard** [comment]
Har oprettet en side på demo med kun en LatestsPostsAllGroups widget:
https://biblo.demo.dbc.dk/latest-posts-all-groups-testside

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK på demo og admin-stg, dog ikke ang. fejlen med manglende posts i LatestPosts widget, som skyldes fejl i referencerne i databasen. Det kræver sandsynligvis, at vi erstatter databasen med en anden database, fx. driftbasen.
