### ISSUE TITLE
Fejl 500 på sider med to "Best rated" widgets

### ISSUE THREAD

**Issue by hrmoller** [DBCDK/biblo-admin#199]
Oprettes der en sektionsside med to Best rated widgets returneres der er en fejl 500 når Biblo forespørger den pågældende side.

På hhv. https://admin-stg.biblo.dk og https://biblo-admin.demo.dbc.dk er der oprettet en sektionsside (`best-rated-test`). Når den pågældende side hentes af Biblo returneres der en fejl 500 og en `Recoverable fatal error` logges til Drupal's log.

Denne issue er oprindeligt oprettet I Biblos repo: https://github.com/DBCDK/biblo/issues/657.

**Comment by vibjerg** [comment]
Fejlen opstår fordi alle felter ikke er udfyldt. Så snart man udfylder alle felter fungerer siden. Jeg lukker dette issue til fordel for #200
