### ISSUE TITLE
Opdater drupal til den seneste version af 8.5

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/biblo-admin#205]
Biblo-admin kører 8.4.8, men skal op at køre på seneste release af 8.5. Det er kun 8.5.x der er supporteret. 

Et indledende forsøg med at opgradere til 8.5.2, resulterede i at menu endpoints ikke længere fungerer, men returnerer "Menu id not found".  Årsagen til fejlen kendes ikke.

**Comment by BettinaAndersen** [comment]
Synes denne har været i done på tavlen?

**Comment by vibjerg** [comment]
Ja, den er fixet og i produktion
