### ISSUE TITLE
Fejl i visning af antal sider med resultater i liste med profiler

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo-admin#85]
https://admin.biblo.dk/admin/dbcdk-community/profiles
Når jeg filtrerer og kun har få resultater i min liste, matcher sidelinks under listen ikke antal sider med resultater.
Med et resultat får jeg stadig "1   2   3   4   5  … Next ›  Last »"
Det bør afspejle det reelle antal sider med resultater.

**Comment by kasperg** [comment]
Dette skulle være rettet.

@AndersFriisBrodsgaard: Vil du teste?

**Comment by AndersFriisBrodsgaard** [comment]
Den er fin, tak
